#!/bin/sh
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/sbackup"

case "$1" in
		upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
		;;
    purge)
        if omv_config_exists $CONFIG; then
            echo "Deleting Configuration..."
            omv_config_delete $CONFIG;
        fi

        if ! omv_config_exists $CONFIG; then
            echo "Configuration Deleted"
        fi
        rm -r /etc/sbackup
        rm -r /var/log/sbackup
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
