#!/bin/sh
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! omv_config_exists "/config/services/sbackup"; then
            echo "Initialize configuration"
            object="<backuplist></backuplist>"
            omv_config_add_element "/config/services" "sbackup" "${object}" true
        fi
        mkdir -p /etc/sbackup/jobs
        mkdir -p /var/log/sbackup/sessionlogs
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

/usr/sbin/omv-mkconf sbackup

exit 0
